version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        #caozj - pgdata:/var/lib/postgresql/data/
        - ../wddata/pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container
        build: ../ddnp/nginx
        restart: always
        ports:
         - "8080:8080"
        # - "80:80"
        volumes:
         #caozj - api_data:/docker_api
         - ./api:/docker_api
         - ../wddata/log:/var/log/nginx
         - ./nginx/static:/docker_api/static
        depends_on:
         - api

    api:
        container_name: api-container
        build: ../ddnp/api
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        # ports:
        # - "8002:8000"
        volumes:
         #caozj - api_data:/docker_api
         - ./api:/docker_api
        depends_on:
         - db

    # auto migrate django
    # migration:
    #     build: ./api
    #     command:
    #         - /bin/sh
    #         - -c
    #         - |
    #           python manage.py collectstatic --noinput
    #           python manage.py migrate
    #           python manage.py makemigrations musics
    #           python manage.py migrate
    #     volumes:
    #     - api_data:/docker_api
    #     depends_on:
    #     - db

volumes:
    #caozj api_data:
    api:
    #caozj pgdata:
    pgdata:
    #caozj
    static:
